#云编译公用核心
name: UBOOT-CORE

on:
  #公用核心标识
  workflow_call:
    inputs:
      UB_TARGET:
        required: true
        type: string
      UB_URL:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  UB_TARGET: ${{inputs.UB_TARGET}}
  UB_URL: ${{inputs.UB_URL}}

jobs:
  ub_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E rm -rf $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "1{s/\r$//;p;q}")
          sudo -E apt -yqq update
          sudo -E apt -yqq purge $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "2{s/\r$//;p;q}")
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq install $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "3{s/\r$//;p;q}")
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Initialization Values
        run: |
          export UB_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export UB_SOURCE=$(echo $UB_URL | cut -d '/' -f 5-)
          export UB_TYPE=$(sed -n "1{s/^#//;s/\r$//;p;q}" $GITHUB_WORKSPACE/Uboots.sh)

          echo "UB_TARGET=$UB_TARGET" >> $GITHUB_ENV
          echo "UB_SOURCE=$UB_SOURCE" >> $GITHUB_ENV
          echo "UB_DATE=$UB_DATE" >> $GITHUB_ENV
          echo "UB_TYPE=$UB_TYPE" >> $GITHUB_ENV

      - name: Clone UBOOT Code
        run: |
          git clone --depth=1 --single-branch $UB_URL ./uboot

      - name: Check Scripts
        run: |
          dos2unix $(find ./ -maxdepth 2 -type f -iname "*.sh")
          chmod +x $(find ./ -maxdepth 2 -type f -iname "*.sh")

      - name: Compile Firmware
        run: |
          cd ./uboot

          $GITHUB_WORKSPACE/Uboots.sh

          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1
          echo "======================="

      - name: Package Firmware
        run: |
          cd ./uboot && mkdir ./upload

          for file in $(find ./output/ -type f -iname "*.*") ; do
            export ext=$(basename "$file" | cut -d '.' -f 2-)
            export name=$(basename "$file" | cut -d '.' -f 1)
            export new_file="$name"_"$UB_DATE"."$ext"
            mv -f "$file" ./upload/"$new_file"
          done

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.UB_TARGET}}_${{env.UB_SOURCE}}_${{env.UB_DATE}}
          files: ./uboot/upload/*.*
          body: |
            这是个平台固件包，内含多个设备！
            请注意选择你需要的设备固件！
            不要问，更就完事了！

            源码：${{env.UB_SOURCE}}
            平台：${{env.UB_TARGET}}
            设备：${{env.UB_TYPE}}

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 2
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
