name: WRT-TEST

on:
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  wrt_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          mkdir ./upload/
          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")" >> $GITHUB_ENV

          sudo -E apt -yqq update
          sudo -E apt -yqq purge android* azure* clang* docker* dotnet* firefox* ghc* golang* google* libclang* libgl1* lld* llvm* mongodb* mono* mysql* nodejs* openjdk* php* powershell* snap* yarn* zulu* temurin* postgresql* microsoft*
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E find / -type d -iregex ".*/\(android.*\|azure.*\|clang.*\|docker.*\|dotnet.*\|firefox.*\|ghc.*\|golang.*\|google.*\|libclang.*\|libgl1.*\|lld.*\|llvm.*\|mongodb.*\|mono.*\|mysql.*\|nodejs.*\|openjdk.*\|php.*\|powershell.*\|snap.*\|yarn.*\|zulu.*\|temurin.*\|postgresql.*\|microsoft.*\)" -prune >> ./upload/TEST.TXT

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: test_${{env.WRT_DATE}}
          files: ./upload/*.*
          body: |
            test_${{env.WRT_DATE}}
